FROM golang:1.13.4
ENV VERSION 1.0.22
ENV GOCACHE /tmp
RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-linux.amd64-$VERSION -O nancy && chmod +x nancy && mv nancy /usr/local/bin/nancy

WORKDIR /go/src/github/stephnangue/movies-parser

RUN go get -u golang.org/x/lint/golint

COPY . .

RUN go get -v 